name: foodyore
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  iconsax_flutter: ^1.0.1
  carousel_slider: ^5.1.1
  lottie: ^3.3.2
  persistent_bottom_nav_bar_v2: ^6.2.0
  intl_phone_field: ^3.2.0
  url_launcher: ^6.3.2
  pinput: ^6.0.1
  intl: ^0.20.2
  image_picker: ^1.2.1

dev_dependencies:
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 24

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/images/
    - assets/picture/
    - assets/icon/

  fonts:
    - family: Athelas
      fonts:
        - asset: assets/fonts/Balthazar-Regular.ttf

    # - family: Garamond
    #   fonts:
    #     - asset: assets/fonts/Garamond Premier Pro Italic.ttf
        
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
